eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/
server:
  port: 8763
spring:
  application:
    name: service-hi
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://217.69.8.97:3306/mysql?zeroDateTimeBehavior=convertToNull&amp;useUnicode=true&amp;characterEncoding=utf-8
    username: root
    password: root
  redis:
    database: 0
    host: 217.69.8.97
    port: 6379
    password: 123456
    timeout: 3000
    max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
    max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
    max-idle: 10      # 连接池中的最大空闲连接
    min-idle: 5       # 连接池中的最小空闲连接
#mybatis config
mybatis:
  typeAliasesPackage: com.forezp.eurekaclient.model
  mapperLocations: classpath*:resources/mapper/*.xml